[build]
  # Use the netlify-build script from package.json
  command = "npm run netlify-build"
  
  # Publish directory - where the built files are located
  publish = "client/dist"
  
  # Base directory for the build
  base = "."
  
  # Environment variables
  [build.environment]
    NODE_VERSION = "18"
    NPM_FLAGS = "--legacy-peer-deps"

# Development settings (for netlify dev)
[dev]
  command = "npm run dev:all"
  port = 5173  # Vite's default port
  targetPort = 5173
  publish = "client/dist"

# Redirect all requests to index.html for client-side routing, except for existing files.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {
    Role = ["!admin"]
  }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {
    Role = ["admin"]
  }

# Configure build settings
[build.processing]
  skip_processing = true
