[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist/public"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
